[tool.poetry]
name = "yobot-remix"
version = "0.1.0"
description = "yobot"
authors = ["Iona <724207289@qq.com>"]
readme = "README.md"
packages = [{ include = "yobot_remix" }]

[tool.poetry.dependencies]
python = "^3.9"
apscheduler = ">=3.6,<4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

