[tool.poetry]
name = "yobot-remix"
version = "0.1.0"
description = "yobot"
authors = ["Iona <724207289@qq.com>"]
readme = "README.md"
packages = [{ include = "yobot_remix" }]

[tool.poetry.dependencies]
python = "^3.9"

aiocqhttp = ">=0.6,<1.0"
aiohttp = ">=3.6.1"
apscheduler = ">=3.6,<4.0"
arrow = ">=0.14,<1.0"
beautifulsoup4 = ">=4.8,<5.0"
expiringdict = ">=1.2.0"
feedparser = ">=6.0,<7.0"
jinja2 = ">=2.11.3,<2.12.0"
markupsafe = ">=2.0.1,<2.1.0"
opencc-python-reimplemented = ">=0.1.5,<0.2.0"
peewee = ">=3.13,<4.0"
quart = ">=0.6.15,<0.7.0"
requests = ">=2.22,<3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = 'aliyun.mirrors'
url = "http://mirrors.aliyun.com/pypi/simple/"

